apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-development
  namespace: rhtap
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/quarkus/overlays/development
    repoURL: https://github.com/keshavr27/quarkuskesav-gitops.git
    targetRevision: main
  destination:
    namespace: kesavramk95-development-development
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
