apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: quarkus 
  janus-idp.io/tekton: quarkus
  backstage.io/kubernetes-id: quarkus
  backstage.io/kubernetes-namespace: kesavramk95-development 
  app.kubernetes.io/part-of: quarkus
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  