apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: quarkus
  janus-idp.io/tekton: quarkus
  backstage.io/kubernetes-id: quarkus
  backstage.io/kubernetes-namespace: kesavramk95-development 
  app.kubernetes.io/part-of: quarkus
resources:
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml
